### ISSUE TITLE
Unexpected Error occurs when attempting to add omnilogic local

### ISSUE THREAD

**Issue by nick2687** [cryptk/haomnilogic-local#117]
When Attempting to add the integration in home assistant it gives me an unexpected error. 

When digging into the logs this is what is returned:

```Logger: custom_components.omnilogic_local.config_flow
Source: custom_components/omnilogic_local/config_flow.py:105
integration: OmniLogic Local (documentation, issues)
First occurred: July 22, 2024 at 12:26:33 PM (4 occurrences)
Last logged: 2:21:15 PM

Unexpected exception: Failed to parse Telemetry: 5 validation errors for Telemetry ColorLogic-Light -> 0 -> @specialEffect field required (type=value_error.missing) VirtualHeater -> 0 -> @SolarSetPoint field required (type=value_error.missing) VirtualHeater -> 0 -> @Mode field required (type=value_error.missing) VirtualHeater -> 0 -> @SilentMode field required (type=value_error.missing) VirtualHeater -> 0 -> @whyHeaterIsOn field required (type=value_error.missing)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyomnilogic_local/models/telemetry.py", line 249, in load_xml
    return Telemetry.parse_obj(data["STATUS"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for Telemetry
ColorLogic-Light -> 0 -> @specialEffect
  field required (type=value_error.missing)
VirtualHeater -> 0 -> @SolarSetPoint
  field required (type=value_error.missing)
VirtualHeater -> 0 -> @Mode
  field required (type=value_error.missing)
VirtualHeater -> 0 -> @SilentMode
  field required (type=value_error.missing)
VirtualHeater -> 0 -> @whyHeaterIsOn
  field required (type=value_error.missing)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/omnilogic_local/config_flow.py", line 105, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/omnilogic_local/config_flow.py", line 51, in validate_input
    telemetry = await omni.async_get_telemetry()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyomnilogic_local/models/util.py", line 43, in wrapper
    return pydantic_type.load_xml(resp_body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyomnilogic_local/models/telemetry.py", line 251, in load_xml
    raise OmniParsingException(f"Failed to parse Telemetry: {exc}") from exc
pyomnilogic_local.exceptions.OmniParsingException: Failed to parse Telemetry: 5 validation errors for Telemetry
ColorLogic-Light -> 0 -> @specialEffect
  field required (type=value_error.missing)
VirtualHeater -> 0 -> @SolarSetPoint
  field required (type=value_error.missing)
VirtualHeater -> 0 -> @Mode
  field required (type=value_error.missing)
VirtualHeater -> 0 -> @SilentMode
  field required (type=value_error.missing)
VirtualHeater -> 0 -> @whyHeaterIsOn
  field required (type=value_error.missing)
  ```

It seems to be missing some values, but I'm not sure why or how to resolve it.

I pulled my omni logic device info for you here as well: 

```
<?xml version="1.0" encoding="UTF-8" ?>
<STATUS version="1.5">
    <Backyard systemId="0" statusVersion="5" airTemp="63" state="1" />
    <BodyOfWater systemId="1" waterTemp="83" flow="255" />
    <Filter systemId="2" filterState="1" filterSpeed="75" valvePosition="1" whyFilterIsOn="14" fpOverride="0" reportedFilterSpeed="75" power="620" lastSpeed="75" />
    <VirtualHeater systemId="3" Current-Set-Point="84" enable="1" />
    <Heater systemId="4" heaterState="1" temp="63" enable="1" priority="0" maintainFor="24" />
    <ValveActuator systemId="5" valveActuatorState="0" whyOn="0" />
    <ColorLogic-Light systemId="6" lightState="0" currentShow="2" speed="4" brightness="4" />
</STATUS>```

**Comment by nick2687** [comment]
Seems the firmware on my hub was the issue. Updating to 4.8 resolved it.

**Comment by ssambhi900** [comment]
@nick2687 - which update did you install from this page?  I just installed R5.0.1 under MSP (Main System Processor)
https://hayward.com/support/resources/firmware

Still not able to connect.
